### ISSUE TITLE
Email just sent 81 email

### ISSUE THREAD

**Issue by mahmadq** [MrMugiwara/Email-Bomb#1]
The troubleshooting?

Traceback (most recent call last):
  File "Email-Bomb.py", line 43, in <module>
    server.sendmail(user,to,msg)
  File "/data/data/com.termux/files/usr/lib/python2.7/smtplib.py", line 736, in sendmail
    self.rset()
  File "/data/data/com.termux/files/usr/lib/python2.7/smtplib.py", line 470, in rset
    return self.docmd("rset")
  File "/data/data/com.termux/files/usr/lib/python2.7/smtplib.py", line 395, in docmd
    return self.getreply()
  File "/data/data/com.termux/files/usr/lib/python2.7/smtplib.py", line 369, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

**Comment by mridul-arora** [comment]
Exactly same happened with me too

**Comment by shanu113** [comment]
Why solve this
